#!/bin/sh

MODDIR=/lib/modules

/etc/init.d/mountvirtfs start
/etc/init.d/portmap start

insmod $MODDIR/e2_proc.ko

/etc/init.d/autofs start

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "Starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin

   echo "Init STMFB"
   insmod $MODDIR/stmcore-display-sti7105.ko
   insmod $MODDIR/stmfb.ko display0=1920x1080-32@60:12m:24m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;

   echo "LOADING MODULES"   
   if [ ! -e /boot/audio.elf ]; then
      echo "FW MISSING!!!"
   fi

   echo "load a firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko type=avs_pio

   player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
   echo "init player $player"

   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   if [ $player -gt 131 ]; then
      insmod $MODDIR/stmvout.ko
      insmod $MODDIR/stmvbi.ko
   fi
   insmod $MODDIR/pseudocard.ko

   #you can change t to c to switch the tuner type
   insmod $MODDIR/spark7162.ko UnionTunerType=t
   if [ $player -gt 131 ]; then
      # Full feature pti
      insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
      if [ $?=='2' ]; then
         # Simple pti
         insmod $MODDIR/pti.ko
      fi
      insmod $MODDIR/stm_monitor.ko
      insmod $MODDIR/stmsysfs.ko
      insmod $MODDIR/stmdvb.ko
   else
      insmod $MODDIR/pti.ko
      insmod $MODDIR/stmdvb.ko
      insmod $MODDIR/stm_monitor.ko
   fi
   insmod $MODDIR/player2.ko
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko
   insmod $MODDIR/smartcard.ko
   insmod $MODDIR/cec.ko activemode=1

   insmod $MODDIR/bpamem.ko
   mknod /dev/bpamem c 153 0 

   echo "init lircd"
   /usr/bin/lircd

   /bin/evremote2 10 100 &

   #stfbcontrol a 255

   /etc/init.d/mountall start
   /etc/init.d/hostname start

   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   /etc/init.d/network start &
   (until false; do echo 1 > /proc/sys/vm/drop_caches; sleep 2; done) &
   
   echo "LOADING xbmc"
   #/etc/init.d/xbmc_userdata
   /usr/lib/xbmc/xbmc.bin 

#never reached
